epc<-read.csv("household_power_consumption.txt",sep=";")
epc$Time<-strptime(paste(epc$Date,epc$Time),format="%d/%m/%Y %H:%M:%S")
epc$Date<-as.Date(epc$Date,format="%d/%m/%Y")
sepc<-subset(epc,Date==as.Date("2007-02-01") | Date==as.Date("2007-02-02"))
sepc$Global_active_power<-as.numeric(as.character(sepc$Global_active_power))
sepc$Global_reactive_power<-as.numeric(as.character(sepc$Global_reactive_power))
sepc$Sub_metering_1<-as.numeric(as.character(sepc$Sub_metering_1))
sepc$Sub_metering_2<-as.numeric(as.character(sepc$Sub_metering_2))
sepc$Sub_metering_3<-as.numeric(as.character(sepc$Sub_metering_3))
sepc$Voltage<-as.numeric(as.character(sepc$Voltage))
par(mfrow=c(2,2))
plot(sepc$Time,sepc$Global_active_power,type="l",ylab="Global active power (kilowatt)",xlab="")
plot(sepc$Time,sepc$Voltage,type="l",ylab="Voltage",xlab="datetime")
plot(sepc$Time,sepc$Sub_metering_1,type="l",ylab="Energy sub metering",xlab="")
points(sepc$Time,sepc$Sub_metering_2,type="l",col="red")
points(sepc$Time,sepc$Sub_metering_3,type="l",col="blue")
legend("topright",col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1,1),cex=0.8,text.width=strwidth("XXXXXXXXXXXXXX"))
plot(sepc$Time,sepc$Global_reactive_power,type="l",ylab="Global reactive power",xlab="datetime")
dev.copy(png,"plot4.png")
dev.off()