epc<-read.csv("household_power_consumption.txt",sep=";")
epc$Time<-strptime(paste(epc$Date,epc$Time),format="%d/%m/%Y %H:%M:%S")
epc$Date<-as.Date(epc$Date,format="%d/%m/%Y")
sepc<-subset(epc,Date==as.Date("2007-02-01") | Date==as.Date("2007-02-02"))
sepc$Global_active_power<-as.numeric(as.character(sepc$Global_active_power))
par(mfrow=c(1,1))
plot(sepc$Time,sepc$Global_active_power,type="l",ylab="Global active power (kilowatt)",xlab="")
dev.copy(png,"plot2.png")
dev.off()
